name: docker and ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  merge_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@production

      - name: Merge changes
        run: git merge --no-ff origin/main

      - name: Push changes
        uses: ad-m/github-push-action@production
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


