name: docker and ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  merge_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch changes
        run: git fetch
      - name: Merge changes
        run: git merge --no-ff origin/main

      - name: Push changes
        run: |
          git config user.name "Dolan001"
          git config user.email "dolankumarbairagi@gmail.com"
          git push origin HEAD:refs/heads/production

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


