name: docker and ci

on:
  push:
    branches: [dolan]

jobs:
  merge-pull-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge dolan -> main
        uses: Dolan001/django-real-time-app@main
        with:
          type: now
          from_branch: dolan
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python app/manage.py test

